org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Parchment mappings (NeoGradle subsystem). See https://parchmentmc.org/docs/getting-started
neogradle.subsystems.parchment.minecraftVersion=1.21.3
neogradle.subsystems.parchment.mappingsVersion=2024.12.07

minecraft_version=1.21.3
minecraft_version_range=[1.21.3,1.21.4)
neo_version=21.3.96
neo_version_range=[21.3,)
loader_version_range=[1,)

mod_id=chemlib
mod_name=ChemLib
mod_license=LGPLv2.1
mod_version=2.1.5
mod_group_id=com.smashingmods.chemlib
mod_authors=DarkArcana
mod_description=ChemLib provides all of the elements of the periodic table and many compounds of those elements. It also includes some items based on the elements and compounds such as ingots and lamps.\nCredits:\n- Andrea Hazard, creator of 'Enhanced Bohr Model' images. Their work is shared under the Creative Commons Attribution-Share Alike 4.0 International license. Read more about the license here: https://creativecommons.org/licenses/by-sa/4.0/deed.en

jei_version=19.27.0.340