@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.smashingmods.chemlib;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;