@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.smashingmods.chemlib.registry;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;