package com.smashingmods.chemlib.datagen;

import com.smashingmods.chemlib.ChemLib;
import net.minecraft.data.DataGenerator;
import net.minecraftforge.common.data.LanguageProvider;

public class LocalizationGenerator extends LanguageProvider {

    public LocalizationGenerator(DataGenerator gen, String locale) {
        super(gen, ChemLib.MODID, locale);
    }

    @Override
    protected void addTranslations() {
        add("item.chemlib.hydrogen", "Hydrogen");
        add("item.chemlib.helium", "Helium");
        add("item.chemlib.lithium", "Lithium");
        add("item.chemlib.beryllium", "Beryllium");
        add("item.chemlib.boron", "Boron");
        add("item.chemlib.carbon", "Carbon");
        add("item.chemlib.nitrogen", "Nitrogen");
        add("item.chemlib.oxygen", "Oxygen");
        add("item.chemlib.fluorine", "Fluorine");
        add("item.chemlib.neon", "Neon");
        add("item.chemlib.sodium", "Sodium");
        add("item.chemlib.magnesium", "Magnesium");
        add("item.chemlib.aluminum", "Aluminum");
        add("item.chemlib.silicon", "Silicon");
        add("item.chemlib.phosphorus", "Phosphorus");
        add("item.chemlib.sulfur", "Sulfur");
        add("item.chemlib.chlorine", "Chlorine");
        add("item.chemlib.argon", "Argon");
        add("item.chemlib.potassium", "Potassium");
        add("item.chemlib.calcium", "Calcium");
        add("item.chemlib.scandium", "Scandium");
        add("item.chemlib.titanium", "Titanium");
        add("item.chemlib.vanadium", "Vanadium");
        add("item.chemlib.chromium", "Chromium");
        add("item.chemlib.manganese", "Manganese");
        add("item.chemlib.iron", "Iron");
        add("item.chemlib.cobalt", "Cobalt");
        add("item.chemlib.nickel", "Nickel");
        add("item.chemlib.copper", "Copper");
        add("item.chemlib.zinc", "Zinc");
        add("item.chemlib.gallium", "Gallium");
        add("item.chemlib.germanium", "Germanium");
        add("item.chemlib.arsenic", "Arsenic");
        add("item.chemlib.selenium", "Selenium");
        add("item.chemlib.bromine", "Bromine");
        add("item.chemlib.krypton", "Krypton");
        add("item.chemlib.rubidium", "Rubidium");
        add("item.chemlib.strontium", "Strontium");
        add("item.chemlib.yttrium", "Yttrium");
        add("item.chemlib.zirconium", "Zirconium");
        add("item.chemlib.niobium", "Niobium");
        add("item.chemlib.molybdenum", "Molybdenum");
        add("item.chemlib.technetium", "Technetium");
        add("item.chemlib.ruthenium", "Ruthenium");
        add("item.chemlib.rhodium", "Rhodium");
        add("item.chemlib.palladium", "Palladium");
        add("item.chemlib.silver", "Silver");
        add("item.chemlib.cadmium", "Cadmium");
        add("item.chemlib.indium", "Indium");
        add("item.chemlib.tin", "Tin");
        add("item.chemlib.antimony", "Antimony");
        add("item.chemlib.tellurium", "Tellurium");
        add("item.chemlib.iodine", "Iodine");
        add("item.chemlib.xenon", "Xenon");
        add("item.chemlib.cesium", "Cesium");
        add("item.chemlib.barium", "Barium");
        add("item.chemlib.lanthanum", "Lanthanum");
        add("item.chemlib.cerium", "Cerium");
        add("item.chemlib.praseodymium", "Praseodymium");
        add("item.chemlib.neodymium", "Neodymium");
        add("item.chemlib.promethium", "Promethium");
        add("item.chemlib.samarium", "Samarium");
        add("item.chemlib.europium", "Europium");
        add("item.chemlib.gadolinium", "Gadolinium");
        add("item.chemlib.terbium", "Terbium");
        add("item.chemlib.dysprosium", "Dysprosium");
        add("item.chemlib.holmium", "Holmium");
        add("item.chemlib.erbium", "Erbium");
        add("item.chemlib.thulium", "Thulium");
        add("item.chemlib.ytterbium", "Ytterbium");
        add("item.chemlib.lutetium", "Lutetium");
        add("item.chemlib.hafnium", "Hafnium");
        add("item.chemlib.tantalum", "Tantalum");
        add("item.chemlib.tungsten", "Tungsten");
        add("item.chemlib.rhenium", "Rhenium");
        add("item.chemlib.osmium", "Osmium");
        add("item.chemlib.iridium", "Iridium");
        add("item.chemlib.platinum", "Platinum");
        add("item.chemlib.gold", "Gold");
        add("item.chemlib.mercury", "Mercury");
        add("item.chemlib.thallium", "Thallium");
        add("item.chemlib.lead", "Lead");
        add("item.chemlib.bismuth", "Bismuth");
        add("item.chemlib.polonium", "Polonium");
        add("item.chemlib.astatine", "Astatine");
        add("item.chemlib.radon", "Radon");
        add("item.chemlib.francium", "Francium");
        add("item.chemlib.radium", "Radium");
        add("item.chemlib.actinium", "Actinium");
        add("item.chemlib.thorium", "Thorium");
        add("item.chemlib.protactinium", "Protactinium");
        add("item.chemlib.uranium", "Uranium");
        add("item.chemlib.neptunium", "Neptunium");
        add("item.chemlib.plutonium", "Plutonium");
        add("item.chemlib.americium", "Americium");
        add("item.chemlib.curium", "Curium");
        add("item.chemlib.berkelium", "Berkelium");
        add("item.chemlib.californium", "Californium");
        add("item.chemlib.einsteinium", "Einsteinium");
        add("item.chemlib.fermium", "Fermium");
        add("item.chemlib.mendelevium", "Mendelevium");
        add("item.chemlib.nobelium", "Nobelium");
        add("item.chemlib.lawrencium", "Lawrencium");
        add("item.chemlib.rutherfordium", "Rutherfordium");
        add("item.chemlib.dubnium", "Dubnium");
        add("item.chemlib.seaborgium", "Seaborgium");
        add("item.chemlib.bohrium", "Bohrium");
        add("item.chemlib.hassium", "Hassium");
        add("item.chemlib.meitnerium", "Meitnerium");
        add("item.chemlib.darmstadtium", "Darmstadtium");
        add("item.chemlib.roentgenium", "Roentgenium");
        add("item.chemlib.copernicium", "Copernicium");
        add("item.chemlib.nihonium", "Nihonium");
        add("item.chemlib.flerovium", "Flerovium");
        add("item.chemlib.moscovium", "Moscovium");
        add("item.chemlib.livermorium", "Livermorium");
        add("item.chemlib.tennessine", "Tennessine");
        add("item.chemlib.oganesson", "Oganesson");

        add("item.chemlib.lithium_ingot", "Lithium Ingot");
        add("item.chemlib.beryllium_ingot", "Beryllium Ingot");
        add("item.chemlib.boron_ingot", "Boron Ingot");
        add("item.chemlib.sodium_ingot", "Sodium Ingot");
        add("item.chemlib.magnesium_ingot", "Magnesium Ingot");
        add("item.chemlib.aluminum_ingot", "Aluminum Ingot");
        add("item.chemlib.silicon_ingot", "Silicon Ingot");
        add("item.chemlib.potassium_ingot", "Potassium Ingot");
        add("item.chemlib.calcium_ingot", "Calcium Ingot");
        add("item.chemlib.scandium_ingot", "Scandium Ingot");
        add("item.chemlib.titanium_ingot", "Titanium Ingot");
        add("item.chemlib.vanadium_ingot", "Vanadium Ingot");
        add("item.chemlib.chromium_ingot", "Chromium Ingot");
        add("item.chemlib.manganese_ingot", "Manganese Ingot");
        add("item.chemlib.cobalt_ingot", "Cobalt Ingot");
        add("item.chemlib.nickel_ingot", "Nickel Ingot");
        add("item.chemlib.copper_ingot", "Copper Ingot");
        add("item.chemlib.zinc_ingot", "Zinc Ingot");
        add("item.chemlib.gallium_ingot", "Gallium Ingot");
        add("item.chemlib.germanium_ingot", "Germanium Ingot");
        add("item.chemlib.arsenic_ingot", "Arsenic Ingot");
        add("item.chemlib.selenium_ingot", "Selenium Ingot");
        add("item.chemlib.rubidium_ingot", "Rubidium Ingot");
        add("item.chemlib.strontium_ingot", "Strontium Ingot");
        add("item.chemlib.yttrium_ingot", "Yttrium Ingot");
        add("item.chemlib.zirconium_ingot", "Zirconium Ingot");
        add("item.chemlib.niobium_ingot", "Niobium Ingot");
        add("item.chemlib.molybdenum_ingot", "Molybdenum Ingot");
        add("item.chemlib.technetium_ingot", "Technetium Ingot");
        add("item.chemlib.ruthenium_ingot", "Ruthenium Ingot");
        add("item.chemlib.rhodium_ingot", "Rhodium Ingot");
        add("item.chemlib.palladium_ingot", "Palladium Ingot");
        add("item.chemlib.silver_ingot", "Silver Ingot");
        add("item.chemlib.cadmium_ingot", "Cadmium Ingot");
        add("item.chemlib.indium_ingot", "Indium Ingot");
        add("item.chemlib.tin_ingot", "Tin Ingot");
        add("item.chemlib.antimony_ingot", "Antimony Ingot");
        add("item.chemlib.tellurium_ingot", "Tellurium Ingot");
        add("item.chemlib.cesium_ingot", "Cesium Ingot");
        add("item.chemlib.barium_ingot", "Barium Ingot");
        add("item.chemlib.lanthanum_ingot", "Lanthanum Ingot");
        add("item.chemlib.cerium_ingot", "Cerium Ingot");
        add("item.chemlib.praseodymium_ingot", "Praseodymium Ingot");
        add("item.chemlib.neodymium_ingot", "Neodymium Ingot");
        add("item.chemlib.promethium_ingot", "Promethium Ingot");
        add("item.chemlib.samarium_ingot", "Samarium Ingot");
        add("item.chemlib.europium_ingot", "Europium Ingot");
        add("item.chemlib.gadolinium_ingot", "Gadolinium Ingot");
        add("item.chemlib.terbium_ingot", "Terbium Ingot");
        add("item.chemlib.dysprosium_ingot", "Dysprosium Ingot");
        add("item.chemlib.holmium_ingot", "Holmium Ingot");
        add("item.chemlib.erbium_ingot", "Erbium Ingot");
        add("item.chemlib.thulium_ingot", "Thulium Ingot");
        add("item.chemlib.ytterbium_ingot", "Ytterbium Ingot");
        add("item.chemlib.lutetium_ingot", "Lutetium Ingot");
        add("item.chemlib.hafnium_ingot", "Hafnium Ingot");
        add("item.chemlib.tantalum_ingot", "Tantalum Ingot");
        add("item.chemlib.tungsten_ingot", "Tungsten Ingot");
        add("item.chemlib.rhenium_ingot", "Rhenium Ingot");
        add("item.chemlib.osmium_ingot", "Osmium Ingot");
        add("item.chemlib.iridium_ingot", "Iridium Ingot");
        add("item.chemlib.platinum_ingot", "Platinum Ingot");
        add("item.chemlib.thallium_ingot", "Thallium Ingot");
        add("item.chemlib.lead_ingot", "Lead Ingot");
        add("item.chemlib.bismuth_ingot", "Bismuth Ingot");
        add("item.chemlib.polonium_ingot", "Polonium Ingot");
        add("item.chemlib.astatine_ingot", "Astatine Ingot");
        add("item.chemlib.francium_ingot", "Francium Ingot");
        add("item.chemlib.radium_ingot", "Radium Ingot");
        add("item.chemlib.actinium_ingot", "Actinium Ingot");
        add("item.chemlib.thorium_ingot", "Thorium Ingot");
        add("item.chemlib.protactinium_ingot", "Protactinium Ingot");
        add("item.chemlib.uranium_ingot", "Uranium Ingot");
        add("item.chemlib.neptunium_ingot", "Neptunium Ingot");
        add("item.chemlib.plutonium_ingot", "Plutonium Ingot");
        add("item.chemlib.americium_ingot", "Americium Ingot");
        add("item.chemlib.curium_ingot", "Curium Ingot");
        add("item.chemlib.berkelium_ingot", "Berkelium Ingot");
        add("item.chemlib.californium_ingot", "Californium Ingot");
        add("item.chemlib.einsteinium_ingot", "Einsteinium Ingot");
        add("item.chemlib.fermium_ingot", "Fermium Ingot");
        add("item.chemlib.mendelevium_ingot", "Mendelevium Ingot");
        add("item.chemlib.nobelium_ingot", "Nobelium Ingot");
        add("item.chemlib.lawrencium_ingot", "Lawrencium Ingot");
        add("item.chemlib.rutherfordium_ingot", "Rutherfordium Ingot");
        add("item.chemlib.dubnium_ingot", "Dubnium Ingot");
        add("item.chemlib.seaborgium_ingot", "Seaborgium Ingot");
        add("item.chemlib.bohrium_ingot", "Bohrium Ingot");
        add("item.chemlib.hassium_ingot", "Hassium Ingot");
        add("item.chemlib.meitnerium_ingot", "Meitnerium Ingot");
        add("item.chemlib.darmstadtium_ingot", "Darmstadtium Ingot");
        add("item.chemlib.roentgenium_ingot", "Roentgenium Ingot");
        add("item.chemlib.copernicium_ingot", "Copernicium Ingot");
        add("item.chemlib.nihonium_ingot", "Nihonium Ingot");
        add("item.chemlib.flerovium_ingot", "Flerovium Ingot");
        add("item.chemlib.moscovium_ingot", "Moscovium Ingot");
        add("item.chemlib.livermorium_ingot", "Livermorium Ingot");
        add("item.chemlib.tennessine_ingot", "Tennessine Ingot");
        add("item.chemlib.oganesson_ingot", "Oganesson Ingot");

        add("item.chemlib.carbon_dioxide_compound", "Carbon Dioxide");
        add("item.chemlib.cellulose_compound", "Cellulose");
        add("item.chemlib.aluminum_oxide_compound", "Aluminum Oxide");
        add("item.chemlib.magnesium_oxide_compound", "Magnesium Oxide");
        add("item.chemlib.potassium_nitrate_compound", "Potassium Nitrate");
        add("item.chemlib.silicon_dioxide_compound", "Silicon Dioxide");
        add("item.chemlib.potassium_chloride_compound", "Potassium Chloride");
        add("item.chemlib.sodium_chloride_compound", "Sodium Chloride");
        add("item.chemlib.water_compound", "Water");
        add("item.chemlib.kaolinite_compound", "Kaolinite");
        add("item.chemlib.protein_compound", "Protein");
        add("item.chemlib.iron_oxide_compound", "Iron Oxide");
        add("item.chemlib.sucrose_compound", "Sucrose");
        add("item.chemlib.calcium_carbonate_compound", "Calcium Carbonate");
        add("item.chemlib.phosphate_compound", "Phosphate");
        add("item.chemlib.hydroxide_compound", "Hydroxide");
        add("item.chemlib.hydroxylapatite_compound", "Hydroxylapatite");
        add("item.chemlib.carbonate_compound", "Carbonate");
        add("item.chemlib.strontium_carbonate_compound", "Strontium Carbonate");
        add("item.chemlib.beryl_compound", "Beryl");
        add("item.chemlib.starch_compound", "Starch");
        add("item.chemlib.psilocybin_compound", "Psilocybin");
        add("item.chemlib.cucurbitacin_compound", "Cucurbitacin");
        add("item.chemlib.zinc_oxide_compound", "Zinc Oxide");
        add("item.chemlib.cobalt_aluminate_compound", "Cobalt Aluminate");
        add("item.chemlib.triglyceride_compound", "Triglyceride");
        add("item.chemlib.lead_iodide_compound", "Lead Iodide");
        add("item.chemlib.urea_compound", "Urea");
        add("item.chemlib.ammonium_compound", "Ammonium");
        add("item.chemlib.diammonium_phosphate_compound", "Diammonium Phosphate");
        add("item.chemlib.amide_compound", "Amide");
        add("item.chemlib.ethanol_compound", "Ethanol");
        add("item.chemlib.potassium_carbonate_compound", "Potassium Carbonate");
        add("item.chemlib.mescaline_compound", "Mescaline");
        add("item.chemlib.mullite_compound", "Mullite");
        add("item.chemlib.methane_compound", "Methane");
        add("item.chemlib.ethane_compound", "Ethane");
        add("item.chemlib.propane_compound", "Propane");
        add("item.chemlib.butane_compound", "Butane");
        add("item.chemlib.pentane_compound", "Pentane");
        add("item.chemlib.hexane_compound", "Hexane");
        add("item.chemlib.potassium_dichromate_compound", "Potassium Dichromate");
        add("item.chemlib.nickel_chloride_compound", "Nickel Chloride");
        add("item.chemlib.potassium_permanganate_compound", "Potassium Permanganate");
        add("item.chemlib.magnesium_sulfate_compound", "Magnesium Sulfate");
        add("item.chemlib.copper_chloride_compound", "Copper Chloride");
        add("item.chemlib.cadmium_sulfide_compound", "Cadmium Sulfide");
        add("item.chemlib.chromium_oxide_compound", "Chromium Oxide");
        add("item.chemlib.antimony_trioxide_compound", "Antimony Trioxide");
        add("item.chemlib.titanium_oxide_compound", "Titanium Oxide");
        add("item.chemlib.han_purple_compound", "Han Purple");
        add("item.chemlib.arsenic_sulfide_compound", "Arsenic Sulfide");
        add("item.chemlib.barium_sulfate_compound", "Barium Sulfate");
        add("item.chemlib.beta_carotene_compound", "β-Carotene");
        add("item.chemlib.polyvinyl_chloride_compound", "Polyvinyl Chloride");
        add("item.chemlib.potassium_cyanide_compound", "Potassium Cyanide");
        add("item.chemlib.epinephrine_compound", "Epinephrine");
        add("item.chemlib.penicillin_compound", "Penicillin");
        add("item.chemlib.acetylsalicylic_acid_compound", "Acetylsalicylic Acid");
        add("item.chemlib.caffeine_compound", "Caffeine");
        add("item.chemlib.mercury_sulfide_compound", "Mercury Sulfide");
        add("item.chemlib.sodium_hydroxide_compound", "Sodium Hydroxide");
        add("item.chemlib.calcium_oxide_compound", "Calcium Oxide");
        add("item.chemlib.calcium_hydroxide_compound", "Calcium Hydroxide");
        add("item.chemlib.calcium_chloride_compound", "Calcium Chloride");
        add("item.chemlib.sodium_carbonate_compound", "Sodium Carbonate");
        add("item.chemlib.hydrochloric_acid_compound", "Hydrochloric Acid");
        add("item.chemlib.magnesium_carbonate_compound", "Magnesium Carbonate");
        add("item.chemlib.lead_oxide_compound", "Lead Oxide");
        add("item.chemlib.sulfur_dioxide_compound", "Sulfur Dioxide");
        add("item.chemlib.lead_sulfide_compound", "Lead Sulfide");
        add("item.chemlib.zinc_sulfide_compound", "Zinc Sulfide");
        add("item.chemlib.iron_disulfide_compound", "Iron Disulfide");
        add("item.chemlib.tin_oxide_compound", "Tin Oxide");
        add("item.chemlib.manganese_oxide_compound", "Manganese Oxide");
        add("item.chemlib.strontium_oxide_compound", "Strontium Oxide");
        add("item.chemlib.iron_ii_oxide_compound", "Iron(II) Oxide");
        add("item.chemlib.sulfuric_acid_compound", "Sulfuric Acid");
        add("item.chemlib.nitric_acid_compound", "Nitric Acid");
        add("item.chemlib.nitrogen_dioxide_compound", "Nitrogen Dioxide");
        add("item.chemlib.sodium_bisulfate_compound", "Sodium Bisulfate");
        add("item.chemlib.ammonia_compound", "Ammonia");
        add("item.chemlib.ammonium_chloride_compound", "Ammonium Chloride");
        add("item.chemlib.phosphoric_acid_compound", "Phosphoric Acid");
        add("item.chemlib.calcium_sulfate_compound", "Calcium Sulfate");
        add("item.chemlib.copper_i_oxide_compound", "Copper(I) Oxide");
        add("item.chemlib.copper_i_sulfide_compound", "Copper(I) Sulfide");
        add("item.chemlib.hydrogen_sulfide_compound", "Hydrogen Sulfide");
        add("item.chemlib.acetylene_compound", "Acetylene");
        add("item.chemlib.acetic_acid_compound", "Acetic Acid");
        add("item.chemlib.nickel_sulfide_compound", "Nickel Sulfide");
        add("item.chemlib.antimony_trisulfide_compound", "Antimony Trisulfide");
        add("item.chemlib.nickel_oxide_compound", "Nickel Oxide");
        add("item.chemlib.carbon_monoxide_compound", "Carbon Monoxide");
        add("item.chemlib.lithium_hydroxide_compound", "Lithium Hydroxide");
        add("item.chemlib.potassium_hydroxide_compound", "Potassium Hydroxide");
        add("item.chemlib.rubidium_hydroxide_compound", "Rubidium Hydroxide");
        add("item.chemlib.cesium_hydroxide_compound", "Cesium Hydroxide");
        add("item.chemlib.beryllium_hydroxide_compound", "Beryllium Hydroxide");
        add("item.chemlib.magnesium_hydroxide_compound", "Magnesium Hydroxide");
        add("item.chemlib.strontium_hydroxide_compound", "Strontium Hydroxide");
        add("item.chemlib.barium_hydroxide_compound", "Barium Hydroxide");
        add("item.chemlib.aluminum_hydroxide_compound", "Aluminum Hydroxide");
        add("item.chemlib.zinc_hydroxide_compound", "Zinc Hydroxide");
        add("item.chemlib.manganese_hydroxide_compound", "Manganese Hydroxide");
        add("item.chemlib.cadmium_hydroxide_compound", "Cadmium Hydroxide");
        add("item.chemlib.copper_ii_hydroxide_compound", "Copper(II) Hydroxide");
        add("item.chemlib.lithium_chloride_compound", "Lithium Chloride");
        add("item.chemlib.rubidium_chloride_compound", "Rubidium Chloride");
        add("item.chemlib.cesium_chloride_compound", "Cesium Chloride");
        add("item.chemlib.beryllium_chloride_compound", "Beryllium Chloride");
        add("item.chemlib.magnesium_chloride_compound", "Magnesium Chloride");
        add("item.chemlib.strontium_chloride_compound", "Strontium Chloride");
        add("item.chemlib.barium_chloride_compound", "Barium Chloride");
        add("item.chemlib.lithium_oxide_compound", "Lithium Oxide");
        add("item.chemlib.sodium_oxide_compound", "Sodium Oxide");
        add("item.chemlib.potassium_oxide_compound", "Potassium Oxide");
        add("item.chemlib.rubidium_oxide_compound", "Rubidium Oxide");
        add("item.chemlib.beryllium_oxide_compound", "Beryllium Oxide");
        add("item.chemlib.barium_oxide_compound", "Barium Oxide");
        add("item.chemlib.lithium_carbonate_compound", "Lithium Carbonate");
        add("item.chemlib.rubidium_carbonate_compound", "Rubidium Carbonate");
        add("item.chemlib.cesium_carbonate_compound", "Cesium Carbonate");
        add("item.chemlib.beryllium_carbonate_compound", "Beryllium Carbonate");
        add("item.chemlib.barium_carbonate_compound", "Barium Carbonate");
        add("item.chemlib.manganese_carbonate_compound", "Manganese Carbonate");
        add("item.chemlib.iron_carbonate_compound", "Iron Carbonate");
        add("item.chemlib.cobalt_carbonate_compound", "Cobalt Carbonate");
        add("item.chemlib.nickel_carbonate_compound", "Nickel Carbonate");
        add("item.chemlib.copper_carbonate_compound", "Copper Carbonate");
        add("item.chemlib.zinc_carbonate_compound", "Zinc Carbonate");
        add("item.chemlib.cadmium_carbonate_compound", "Cadmium Carbonate");
        add("item.chemlib.lead_carbonate_compound", "Lead Carbonate");
        add("item.chemlib.lithium_sulfate_compound", "Lithium Sulfate");
        add("item.chemlib.sodium_sulfate_compound", "Sodium Sulfate");
        add("item.chemlib.potassium_sulfate_compound", "Potassium Sulfate");
        add("item.chemlib.rubidium_sulfate_compound", "Rubidium Sulfate");
        add("item.chemlib.cesium_sulfate_compound", "Cesium Sulfate");
        add("item.chemlib.beryllium_sulfate_compound", "Beryllium Sulfate");
        add("item.chemlib.strontium_sulfate_compound", "Strontium Sulfate");
        add("item.chemlib.manganese_sulfate_compound", "Manganese Sulfate");
        add("item.chemlib.cobalt_sulfate_compound", "Cobalt Sulfate");
        add("item.chemlib.nickel_sulfate_compound", "Nickel Sulfate");
        add("item.chemlib.iron_ii_sulfate_compound", "Iron(II) Sulfate");
        add("item.chemlib.copper_ii_sulfate_compound", "Copper(II) Sulfate");
        add("item.chemlib.zinc_sulfate_compound", "Zinc Sulfate");
        add("item.chemlib.cadmium_sulfate_compound", "Cadmium Sulfate");
        add("item.chemlib.lead_sulfate_compound", "Lead Sulfate");
        add("item.chemlib.tin_sulfate_compound", "Tin Sulfate");
        add("item.chemlib.nitrate_compound", "Nitrate");
        add("item.chemlib.lithium_nitrate_compound", "Lithium Nitrate");
        add("item.chemlib.sodium_nitrate_compound", "Sodium Nitrate");
        add("item.chemlib.rubidium_nitrate_compound", "Rubidium Nitrate");
        add("item.chemlib.cesium_nitrate_compound", "Cesium Nitrate");
        add("item.chemlib.beryllium_nitrate_compound", "Beryllium Nitrate");
        add("item.chemlib.magnesium_nitrate_compound", "Magnesium Nitrate");
        add("item.chemlib.calcium_nitrate_compound", "Calcium Nitrate");
        add("item.chemlib.strontium_nitrate_compound", "Strontium Nitrate");
        add("item.chemlib.barium_nitrate_compound", "Barium Nitrate");
        add("item.chemlib.manganese_nitrate_compound", "Manganese Nitrate");
        add("item.chemlib.iron_iii_nitrate_compound", "Iron(III) Nitrate");
        add("item.chemlib.cobalt_nitrate_compound", "Cobalt Nitrate");
        add("item.chemlib.nickel_nitrate_compound", "Nickel Nitrate");
        add("item.chemlib.copper_nitrate_compound", "Copper Nitrate");
        add("item.chemlib.zinc_nitrate_compound", "Zinc Nitrate");
        add("item.chemlib.lead_nitrate_compound", "Lead Nitrate");
        add("item.chemlib.cadmium_nitrate_compound", "Cadmium Nitrate");
        add("item.chemlib.aluminum_nitrate_compound", "Aluminum Nitrate");
        add("item.chemlib.nitric_oxide_compound", "Nitric Oxide");
        add("item.chemlib.carbon_disulfide_compound", "Carbon Disulfide");
        add("item.chemlib.potassium_ethyl_xanthate_compound", "Potassium Ethyl Xanthate");
        add("item.chemlib.sulfur_trioxide_compound", "Sulfur Trioxide");
        add("item.chemlib.barium_sulfide_compound", "Barium Sulfide");
        add("block.chemlib.argon_lamp", "Argon Lamp");
        add("block.chemlib.helium_lamp", "Helium Lamp");
        add("block.chemlib.krypton_lamp", "Krypton Lamp");
        add("block.chemlib.neon_lamp", "Neon Lamp");
        add("block.chemlib.xenon_lamp", "Xenon Lamp");
        
        add("itemGroup.chemlib", "Chemistry");
    }
}
