@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.smashingmods.chemlib.datagen;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;